package com.example.Lesbarkeit.Enums;

public enum MetricsType {
    FLESCH_KINCAID, AUTOMATED_READABILITY_INDEX, COLEMAN_LIAU,FLESCH_READING_EASE,GUNNING_FOG, SMOG_INDEX, CHARACTERS, SYLLABLES, WORDS, COMPLEXWORDS, SENTENCE,;
}
